name = "boostocks"
compatibility_date = "2023-11-01"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
pages_build_output_dir = "out"

# For local development
[dev]
port = 8787

# Optional D1 database binding
# This binding is optional and won't cause failures if not available
[[ d1_databases ]]
binding = "DB"
database_name = "boostocks_waitlist" 
database_id = "deb28144-15bc-4362-8fe1-6e2e6f07d2e5"
preview_database_id = "deb28144-15bc-4362-8fe1-6e2e6f07d2e5"

[vars]
ADMIN_EMAIL = "admin@boostocks.com"
